version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "vue",
    "ember",
    "meteor",
    "angularjs"
  ]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "17"

[[analyzers]]
name = "php"
enabled = true