version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/4k4xs4pH1r3/artemisa"
  dependencies_vendored = true

[[analyzers]]
name = "php"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "1.30.0"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "19"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "vue",
    "ember",
    "angularjs",
    "meteor"
  ]
  environment = [
    "nodejs",
    "jquery",
    "mongo",
    "browser",
    "jest",
    "cypress",
    "vitest",
    "mocha",
    "jasmine"
  ]

[[analyzers]]
name = "csharp"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "standardrb"

[[transformers]]
name = "scalafmt"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "yapf"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "php-cs-fixer"

[[transformers]]
name = "rustfmt"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "ruff"

[[transformers]]
name = "dotnet-format"